[project]
name = "tokledger"
version = "0.1.0"
description = "Persistent tokscale statistics no matter where your agents live"
readme = "README.md"
authors = [
    { name = "Israel Flores-Arbolay", email = "israelflores8789@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []
dynamic = ["version"]

[project.scripts]
tokledger = "tokledger:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]
